import { localDate } from './parser.js';
import { confirmAction, deleteOwned } from './confirm.js';

const presets = ['Bank Jago','Bank DKI','ShopeePay','GoPay','OVO','Tunai'];
const money = amount => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(amount);
const esc = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const valid = value => Number.isSafeInteger(value) && value >= 0;

export function accountBalance(account,rows,transfers) {
  const transactions=rows.filter(row=>row.account_id===account.id).reduce((sum,row)=>sum+(row.kind==='income'?Number(row.amount):-Number(row.amount)),0);
  const movement=transfers.reduce((sum,row)=>sum+(row.to_account_id===account.id?Number(row.amount):0)-(row.from_account_id===account.id?Number(row.amount):0),0);
  return Number(account.opening_balance)+transactions+movement;
}

export function createAccounts(db,notify,getRows,reload,getUserId) {
  let accounts=[],transfers=[];
  const root=()=>document.querySelector('#dashboard');
  const fail=e=>notify(e.message||'Gagal menyimpan akun.',true);
  async function load(){const [a,t]=await Promise.all([db.from('money_accounts').select('id,name,opening_balance,created_at').order('created_at'),db.from('account_transfers').select('id,from_account_id,to_account_id,amount,occurred_on,note,created_at').order('occurred_on',{ascending:false}).order('created_at',{ascending:false})]);if(a.error||t.error)throw a.error||t.error;accounts=a.data||[];transfers=t.data||[];}
  const options=(selected='')=>`<option value="">Belum ditentukan</option>${accounts.map(a=>`<option value="${a.id}" ${a.id===selected?'selected':''}>${esc(a.name)}</option>`).join('')}`;
  const name=id=>accounts.find(a=>a.id===id)?.name||'Akun dihapus';
  function render(){
    const rows=getRows(),total=accounts.reduce((sum,a)=>sum+accountBalance(a,rows,transfers),0),unassigned=rows.filter(row=>!row.account_id).length;
    root().innerHTML=`<div class="feature-grid"><section class="feature-card"><span class="eyebrow">SEMUA AKUN</span><h2>Total saldo ${money(total)}</h2><p class="muted">Saldo awal + pemasukan − pengeluaran + transfer. ${unassigned} transaksi lama belum ditentukan akunnya dan belum memengaruhi saldo di sini.</p>${!accounts.length?'<button class="secondary" id="add-presets">Buat Bank Jago, Bank DKI, ShopeePay, GoPay, OVO, dan Tunai</button>':''}<form id="account-form" class="feature-form"><label>Nama akun<input name="name" maxlength="80" required placeholder="Contoh: Bank Jago"></label><label>Saldo awal (Rp)<input name="balance" type="number" min="0" step="1" required value="0"></label><button class="primary">Tambah akun</button></form><small class="muted">Isi saldo awal sebelum transaksi yang akan kamu tautkan. Transaksi lama bisa dipilih akunnya melalui tombol Ubah di riwayat.</small></section><section class="feature-card"><span class="eyebrow">PINDAH DANA</span><h2>Transfer antar akun</h2><p class="muted">Transfer hanya memindahkan saldo; laporan pemasukan dan pengeluaran tidak berubah.</p><form id="transfer-form" class="feature-form"><label>Dari<select name="from" required>${accounts.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select></label><label>Ke<select name="to" required>${accounts.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select></label><label>Nominal (Rp)<input name="amount" type="number" min="1" step="1" required></label><label>Tanggal<input name="date" type="date" required value="${localDate()}"></label><label>Catatan<input name="note" maxlength="160" placeholder="Opsional"></label><button class="primary" ${accounts.length<2?'disabled':''}>Simpan transfer</button></form></section></div><div class="goal-list">${accounts.map(a=>`<section class="feature-card"><div class="feature-row"><div><span class="eyebrow">AKUN / DOMPET</span><h2>${esc(a.name)}</h2></div><button class="delete" data-account-delete="${a.id}">Hapus</button></div><strong class="feature-total">${money(accountBalance(a,rows,transfers))}</strong><form class="feature-form account-edit" data-id="${a.id}"><label>Ubah nama<input name="name" maxlength="80" required value="${esc(a.name)}"></label><label>Saldo awal (Rp)<input name="balance" type="number" min="0" step="1" required value="${a.opening_balance}"></label><button class="secondary">Simpan perubahan</button></form></section>`).join('')}</div><section class="feature-card transfer-history"><span class="eyebrow">RIWAYAT TRANSFER</span><h2>Perpindahan dana</h2>${transfers.length?transfers.map(t=>`<div class="calendar-item"><span><strong>${esc(name(t.from_account_id))} → ${esc(name(t.to_account_id))}</strong><small>${esc(t.occurred_on)}${t.note?' · '+esc(t.note):''}</small></span><strong>${money(t.amount)}</strong><button class="delete" data-transfer-delete="${t.id}">Hapus</button></div>`).join(''):'<p class="muted">Belum ada transfer.</p>'}</section>`;
    root().querySelector('#add-presets')?.addEventListener('click',async event=>{event.currentTarget.disabled=true;const {error}=await db.from('money_accounts').upsert(presets.map(name=>({user_id:getUserId(),name,opening_balance:0})),{onConflict:'user_id,name',ignoreDuplicates:true});if(error)return fail(error);await reload();});
    root().querySelector('#account-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,balance=Number(f.elements.balance.value);if(!valid(balance))return notify('Saldo awal tidak valid.',true);const {error}=await db.from('money_accounts').insert({name:f.elements.name.value.trim(),opening_balance:balance});if(error)return fail(error);notify('Akun dibuat.');await reload();};
    root().querySelectorAll('.account-edit').forEach(form=>form.onsubmit=async e=>{e.preventDefault();const balance=Number(form.elements.balance.value);if(!valid(balance))return notify('Saldo awal tidak valid.',true);const {error}=await db.from('money_accounts').update({name:form.elements.name.value.trim(),opening_balance:balance}).eq('id',form.dataset.id);if(error)return fail(error);notify('Akun diperbarui.');await reload();});
    root().querySelector('#transfer-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,from=f.elements.from.value,to=f.elements.to.value,amount=Number(f.elements.amount.value);if(!from||!to||from===to||!valid(amount)||amount===0)return notify('Pilih dua akun berbeda dan nominal yang valid.',true);const source=accounts.find(a=>a.id===from);if(amount>accountBalance(source,getRows(),transfers))return notify('Saldo akun asal tidak cukup.',true);const {error}=await db.from('account_transfers').insert({from_account_id:from,to_account_id:to,amount,occurred_on:f.elements.date.value,note:f.elements.note.value.trim()});if(error)return fail(error);notify('Transfer tersimpan.');await reload();};
    root().querySelectorAll('[data-transfer-delete]').forEach(button=>button.onclick=async()=>{if(!await confirmAction('Hapus transfer ini? Saldo kedua akun akan dihitung ulang.'))return;try{await deleteOwned(db,'account_transfers',button.dataset.transferDelete);}catch(e){return fail(e);}await reload();});
    root().querySelectorAll('[data-account-delete]').forEach(button=>button.onclick=async()=>{if(!await confirmAction('Hapus akun ini? Akun yang sudah punya transaksi atau transfer tidak dapat dihapus.'))return;try{await deleteOwned(db,'money_accounts',button.dataset.accountDelete);}catch(e){return fail(e);}await reload();});
  }
  return {load,render,options,nameOf:id=>accounts.find(account=>account.id===id)?.name||''};
}
