const money = value => new Intl.NumberFormat('id-ID', {style:'currency',currency:'IDR',maximumFractionDigits:0}).format(value);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const validAmount = value => Number.isSafeInteger(value) && value > 0;
export function splitEvenly(total, count) {
  if (!validAmount(total) || !Number.isInteger(count) || count < 2 || count > 30 || total < count) throw new Error('Isi total dan minimal dua orang.');
  const base = Math.floor(total / count);
  return Array.from({length:count}, (_, index) => base + (index < total % count ? 1 : 0));
}
export function createFeatures(db, notify, getView) {
  let goals = [], entries = [], bills = [];
  const root = () => document.querySelector('#dashboard');
  const showError = error => notify(error.message || 'Gagal menyimpan. Coba lagi.', true);
  async function load() {
    const results = await Promise.all([
      db.from('savings_goals').select('id,name,target_amount,created_at').order('created_at',{ascending:false}),
      db.from('savings_entries').select('id,goal_id,kind,amount,note,created_at').order('created_at',{ascending:false}),
      db.from('split_bills').select('id,title,total_amount,participants,created_at').order('created_at',{ascending:false})
    ]);
    const error = results.find(result => result.error)?.error;
    if (error) throw error;
    [goals,entries,bills] = results.map(result => result.data || []);
  }
  const balance = id => entries.filter(e => e.goal_id === id).reduce((sum,e) => sum + (e.kind === 'deposit' ? e.amount : -e.amount),0);
  function renderSavings() {
    root().innerHTML = `<div class="feature-grid"><section class="feature-card"><span class="eyebrow">TARGET BARU</span><h2>Buat tabungan</h2><form id="goal-form" class="feature-form"><label>Nama target<input name="name" maxlength="80" required placeholder="Contoh: Dana darurat"></label><label>Target (Rp)<input name="target" type="number" min="1" step="1" required placeholder="5000000"></label><button class="primary">Buat target</button></form></section><section class="feature-card"><span class="eyebrow">PROGRES</span><h2>Tabunganku</h2><p class="muted">Setoran di sini adalah catatan alokasi dana dan tidak mengubah laporan pemasukan/pengeluaran.</p><strong class="feature-total">${money(goals.reduce((sum,goal)=>sum+balance(goal.id),0))}</strong><span class="muted">Total dana di semua target</span></section></div><div class="goal-list">${goals.length ? goals.map(goal => {const saved=balance(goal.id),pct=Math.min(100,Math.max(0,saved/goal.target_amount*100));return `<section class="feature-card goal-card"><div class="feature-row"><div><span class="eyebrow">TARGET TABUNGAN</span><h2>${esc(goal.name)}</h2></div><button class="delete" data-remove-goal="${goal.id}" aria-label="Hapus target ${esc(goal.name)}">Hapus</button></div><div class="goal-amount"><strong>${money(saved)}</strong><span>dari ${money(goal.target_amount)}</span></div><div class="progress"><span style="width:${pct}%;background:#3a8890"></span></div><small>${Math.round(pct)}% tercapai</small><form class="feature-form entry-form" data-goal="${goal.id}"><label>Nominal (Rp)<input name="amount" type="number" min="1" step="1" required placeholder="100000"></label><label>Catatan<input name="note" maxlength="160" placeholder="Opsional"></label><div class="feature-actions"><button class="primary" name="kind" value="deposit">Tambah setoran</button><button class="secondary" name="kind" value="withdraw">Tarik dana</button></div></form><div class="entry-list">${entries.filter(e=>e.goal_id===goal.id).slice(0,10).map(e=>`<div class="entry-row"><span>${e.kind==='deposit'?'Setoran':'Penarikan'}${e.note?' · '+esc(e.note):''}<small>${new Date(e.created_at).toLocaleDateString('id-ID',{timeZone:'Asia/Jakarta'})}</small></span><strong class="${e.kind==='deposit'?'positive':'negative'}">${e.kind==='deposit'?'+':'−'}${money(e.amount)}</strong></div>`).join('') || '<p class="muted">Belum ada setoran.</p>'}</div></section>`;}).join('') : '<div class="feature-card feature-empty">Belum ada target. Buat target tabungan pertamamu di atas.</div>'}</div>`;
    document.querySelector('#goal-form').onsubmit=async event=>{event.preventDefault();const f=event.currentTarget;const target=Number(f.elements.target.value);if(!validAmount(target))return notify('Target harus lebih dari nol.',true);const {error}=await db.from('savings_goals').insert({name:f.elements.name.value.trim(),target_amount:target});if(error)return showError(error);notify('Target tabungan dibuat.');await refresh('savings');};
    document.querySelectorAll('.entry-form').forEach(form=>form.onsubmit=async event=>{event.preventDefault();const kind=event.submitter?.value || 'deposit',amount=Number(form.elements.amount.value),goalId=form.dataset.goal;if(!validAmount(amount))return notify('Nominal harus lebih dari nol.',true);if(kind==='withdraw'&&amount>balance(goalId))return notify('Penarikan melebihi dana yang tersedia.',true);const {error}=await db.from('savings_entries').insert({goal_id:goalId,kind,amount,note:form.elements.note.value.trim()});if(error)return showError(error);notify(kind==='deposit'?'Setoran tercatat.':'Penarikan tercatat.');await refresh('savings');});
    document.querySelectorAll('[data-remove-goal]').forEach(button=>button.onclick=async()=>{if(!confirm('Hapus target beserta semua riwayat setoran dan penarikannya?'))return;const {error}=await db.from('savings_goals').delete().eq('id',button.dataset.removeGoal);if(error)return showError(error);notify('Target dihapus.');await refresh('savings');});
  }
  function renderSplit() {
    root().innerHTML = `<div class="feature-grid"><section class="feature-card"><span class="eyebrow">TAGIHAN BARU</span><h2>Hitung split bill</h2><form id="bill-form" class="feature-form"><label>Nama tagihan<input name="title" maxlength="100" required placeholder="Contoh: Makan malam"></label><label>Total akhir termasuk pajak (Rp)<input name="total" type="number" min="1" step="1" required placeholder="125000"></label><label>Nama orang, pisahkan dengan koma atau baris baru<textarea name="names" required placeholder="Rahmalia, Dini, Andi"></textarea></label><button class="primary">Hitung dan simpan</button></form></section><section class="feature-card"><span class="eyebrow">CARA KERJA</span><h2>Patungan lebih rapi</h2><p class="muted">Masukkan total pada struk setelah pajak dan nama semua orang, termasuk kamu bila ikut patungan. Sistem membagi rata hingga rupiah terakhir. Tandai orang yang sudah membayar.</p><p class="muted">Split bill tersimpan terpisah dari transaksi. Catat pengeluaranmu sendiri lewat chat jika ingin muncul di laporan bulanan.</p></section></div><div class="bill-list">${bills.length ? bills.map(bill=>{const people=Array.isArray(bill.participants)?bill.participants:[];const paid=people.filter(p=>p.paid).reduce((sum,p)=>sum+Number(p.amount),0);return `<section class="feature-card bill-card"><div class="feature-row"><div><span class="eyebrow">SPLIT BILL</span><h2>${esc(bill.title)}</h2><small>${new Date(bill.created_at).toLocaleDateString('id-ID',{timeZone:'Asia/Jakarta'})}</small></div><button class="delete" data-remove-bill="${bill.id}" aria-label="Hapus tagihan ${esc(bill.title)}">Hapus</button></div><div class="bill-summary"><strong>${money(bill.total_amount)}</strong><span>${people.length} orang · Terbayar ${money(paid)}</span></div><div class="bill-people">${people.map((p,index)=>`<label class="bill-person"><input type="checkbox" data-bill="${bill.id}" data-person="${index}" ${p.paid?'checked':''}><span>${esc(p.name)}</span><strong>${money(Number(p.amount))}</strong></label>`).join('')}</div></section>`;}).join('') : '<div class="feature-card feature-empty">Belum ada tagihan. Buat split bill pertamamu di atas.</div>'}</div>`;
    document.querySelector('#bill-form').onsubmit=async event=>{event.preventDefault();const f=event.currentTarget,total=Number(f.elements.total.value),names=f.elements.names.value.split(/[,\n]+/).map(n=>n.trim()).filter(Boolean);if(names.length<2||names.length>30||!validAmount(total)||total<names.length)return notify('Isi total dan 2–30 nama orang.',true);const amounts=splitEvenly(total,names.length),participants=names.map((name,i)=>({name:name.slice(0,80),amount:amounts[i],paid:false}));const {error}=await db.from('split_bills').insert({title:f.elements.title.value.trim(),total_amount:total,participants});if(error)return showError(error);notify('Split bill tersimpan.');await refresh('split');};
    document.querySelectorAll('[data-person]').forEach(input=>input.onchange=async()=>{const bill=bills.find(b=>b.id===input.dataset.bill);const participants=bill.participants.map((p,i)=>i===Number(input.dataset.person)?{...p,paid:input.checked}:p);input.disabled=true;const {error}=await db.from('split_bills').update({participants}).eq('id',bill.id);if(error){input.checked=!input.checked;input.disabled=false;return showError(error);}await refresh('split');});
    document.querySelectorAll('[data-remove-bill]').forEach(button=>button.onclick=async()=>{if(!confirm('Hapus split bill ini?'))return;const {error}=await db.from('split_bills').delete().eq('id',button.dataset.removeBill);if(error)return showError(error);notify('Split bill dihapus.');await refresh('split');});
  }
  async function refresh(view) {try {root().innerHTML='<div class="feature-card feature-empty">Memuat data…</div>';await load();if(getView()!==view)return;if(view==='savings')renderSavings();else renderSplit();}catch(error){root().innerHTML='<div class="feature-card feature-empty">Gagal memuat data. Buka menu ini lagi untuk mencoba ulang.</div>';showError(error);}}
  return {refresh};
}
