import { createIcons, ArrowDownLeft, ArrowUpRight, BarChart3, CalendarDays, Check, ChevronLeft, ChevronRight, CircleHelp, Download, Plus, Send, Trash2, Upload, Wallet, X } from 'lucide';
import { CATEGORIES, localDate, parseTransaction } from './parser.js';
import './style.css';

const STORAGE_KEY = 'arus-transactions-v1';
const icons = { ArrowDownLeft, ArrowUpRight, BarChart3, CalendarDays, Check, ChevronLeft, ChevronRight, CircleHelp, Download, Plus, Send, Trash2, Upload, Wallet, X };
const $ = (s) => document.querySelector(s);
const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = n => new Intl.NumberFormat('id-ID', { style:'currency', currency:'IDR', maximumFractionDigits:0 }).format(n);
const monthName = d => new Intl.DateTimeFormat('id-ID', { month:'long', year:'numeric', timeZone:'UTC' }).format(new Date(`${d}-01T00:00:00Z`));
const state = { month:localDate().slice(0,7), rows:[], draft:null, tab:'all', view:'overview', loading:false };
const icon = (name, size=19) => `<i data-lucide="${name}" style="width:${size}px;height:${size}px"></i>`;
function activateIcons(){ createIcons({ icons, attrs:{'stroke-width':1.8} }); }
function toast(msg, error=false){ const el=$('#toast'); el.textContent=msg; el.className=`toast show ${error?'error':''}`; clearTimeout(toast.timer); toast.timer=setTimeout(()=>el.className='toast',3500); }

function readStored(){ try { const value=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]'); return Array.isArray(value)?value:[]; } catch { return []; } }
function persist(rows){ try { localStorage.setItem(STORAGE_KEY,JSON.stringify(rows)); return true; } catch { toast('Penyimpanan browser penuh atau tidak tersedia.',true); return false; } }
function backup(){ const blob=new Blob([JSON.stringify({version:1,exported_at:new Date().toISOString(),transactions:readStored()},null,2)],{type:'application/json'}); const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`arus-cadangan-${localDate()}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000); }
async function restore(file){try{const data=JSON.parse(await file.text());if(data.version!==1||!Array.isArray(data.transactions)||!data.transactions.every(r=>typeof r.id==='string'&&['income','expense'].includes(r.kind)&&Number.isSafeInteger(r.amount)&&r.amount>0&&typeof r.category==='string'&&typeof r.description==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(r.occurred_on)&&typeof r.created_at==='string'))throw new Error('Format cadangan tidak valid.');if(!confirm(`Pulihkan ${data.transactions.length} transaksi? Catatan di perangkat ini akan diganti.`))return;if(persist(data.transactions)){load();toast('Cadangan berhasil dipulihkan.');}}catch(error){toast(error.message||'Gagal membaca cadangan.',true);}}

function shell(){
  $('#app').innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand"><span class="mark">a.</span><span>arus</span></div><div class="side-caption">RUANG PRIBADI</div><button class="side-nav active" data-view="overview">${icon('BarChart3')} Ringkasan</button><button class="side-nav" data-view="report">${icon('CalendarDays')} Laporan bulanan</button><div class="side-bottom"><div class="avatar">A</div><div class="account"><strong>Perangkat ini</strong><span>Data tersimpan di browser</span></div><button class="icon-button" id="restore" title="Pulihkan cadangan" aria-label="Pulihkan cadangan">${icon('Upload')}</button><button class="icon-button" id="backup" title="Unduh cadangan" aria-label="Unduh cadangan">${icon('Download')}</button></div></aside><main class="content"><header class="topbar"><div class="mobile-brand"><span class="mark">a.</span><span>arus</span></div><span>Keuangan pribadi</span><span class="top-date">${icon('CalendarDays',16)} ${new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Jakarta'}).format(new Date())}</span></header><div class="main-inner"><div class="mobile-nav"><button class="active" data-view="overview">Ringkasan</button><button data-view="report">Laporan bulanan</button></div><section class="heading"><div><span class="eyebrow" id="page-kicker">DASHBOARD</span><h1 id="page-title">Ringkasan keuangan</h1><p id="page-description">Pantau uang masuk dan keluar dalam satu tempat. Data tersimpan di browser perangkat ini.</p></div><div class="month-control"><button id="prev" aria-label="Bulan sebelumnya">${icon('ChevronLeft',18)}</button><span>${esc(monthName(state.month))}</span><button id="next" aria-label="Bulan berikutnya">${icon('ChevronRight',18)}</button></div></section><div id="dashboard"></div></div></main></div><div id="toast" class="toast"></div>`;
  const mobileBackup=document.createElement('button');mobileBackup.className='mobile-logout';mobileBackup.setAttribute('aria-label','Unduh cadangan');mobileBackup.innerHTML=icon('Download',18);$('.topbar').append(mobileBackup);mobileBackup.onclick=backup;const mobileRestore=document.createElement('button');mobileRestore.className='mobile-logout';mobileRestore.setAttribute('aria-label','Pulihkan cadangan');mobileRestore.innerHTML=icon('Upload',18);$('.topbar').append(mobileRestore);mobileRestore.onclick=()=>$('#restore-file').click();
  const fileInput=document.createElement('input');fileInput.id='restore-file';fileInput.type='file';fileInput.accept='application/json,.json';fileInput.hidden=true;document.body.append(fileInput);fileInput.onchange=async()=>{if(fileInput.files?.[0])await restore(fileInput.files[0]);fileInput.value='';};$('#restore').onclick=()=>fileInput.click();$('#backup').onclick=backup; $('#prev').onclick=()=>shift(-1);$('#next').onclick=()=>shift(1);document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>switchView(button.dataset.view));activateIcons();renderDashboard();
}
function shift(delta){const [y,m]=state.month.split('-').map(Number);const d=new Date(Date.UTC(y,m-1+delta,1));state.month=d.toISOString().slice(0,7);load();}
function switchView(view){state.view=view;document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===view));$('#page-kicker').textContent=view==='report'?'LAPORAN':'DASHBOARD';$('#page-title').textContent=view==='report'?'Laporan bulanan':'Ringkasan keuangan';$('#page-description').textContent=view==='report'?'Rincian pemasukan dan pengeluaran selama bulan yang dipilih.':'Pantau uang masuk dan keluar dalam satu tempat. Data tersimpan di browser perangkat ini.';renderDashboard();}
function totals(){let income=0,expense=0;for(const row of state.rows) row.kind==='income'?income+=row.amount:expense+=row.amount;return {income,expense};}
function renderDashboard(){
  if(state.view==='report'){renderReport();return;}
  const {income,expense}=totals();const balance=income-expense;
  $('#dashboard').innerHTML=`<div class="stat-grid"><div class="stat hero-stat"><div class="stat-title">Saldo bulan ini <span>${icon('Wallet',19)}</span></div><div class="stat-value">${money(balance)}</div><div class="stat-foot">${balance>=0?'Pemasukan lebih besar dari pengeluaran':'Pengeluaran melebihi pemasukan'}</div></div><div class="stat"><div class="stat-title">Pemasukan <span class="badge income">${icon('ArrowDownLeft',18)}</span></div><div class="stat-value">${money(income)}</div><div class="stat-foot">Total bulan ini</div></div><div class="stat"><div class="stat-title">Pengeluaran <span class="badge expense">${icon('ArrowUpRight',18)}</span></div><div class="stat-value">${money(expense)}</div><div class="stat-foot">Total bulan ini</div></div></div><div class="workspace"><section class="chat-panel"><div class="panel-head"><div><span class="eyebrow">CATAT TRANSAKSI</span><h2>Catat lewat chat</h2></div><span class="chat-status">Siap mencatat</span></div><div class="conversation"><div class="bot-bubble"><span class="bot-avatar">a.</span><div><strong>Halo! Mau mencatat apa hari ini?</strong><p>Ceritakan seperti sedang chat. Aku bantu baca nominal dan kategorinya.</p></div></div><div class="examples"><span>Coba tulis:</span><button data-example="Kopi susu 25 ribu tadi pagi">“Kopi susu 25 ribu tadi pagi”</button><button data-example="Terima gaji 8 juta hari ini">“Terima gaji 8 juta hari ini”</button></div><div id="chat-output"></div></div><form id="chat-form" class="chat-form"><label class="sr-only" for="chat-input">Tulis transaksi</label><input id="chat-input" placeholder="Contoh: makan siang 35 ribu" autocomplete="off" maxlength="240"><button aria-label="Kirim catatan" type="submit">${icon('Send',19)}</button></form><div class="chat-hint">${icon('CircleHelp',15)} Tinjau hasilnya sebelum menyimpan.</div></section><section class="category-panel"><div class="panel-head"><div><span class="eyebrow">PENGELUARAN</span><h2>Menurut kategori</h2></div></div>${categoryHtml(expense)}</section></div><section class="history"><div class="history-head"><div><span class="eyebrow">AKTIVITAS</span><h2>Riwayat transaksi</h2></div><div class="filters"><button data-tab="all" class="${state.tab==='all'?'active':''}">Semua</button><button data-tab="expense" class="${state.tab==='expense'?'active':''}">Pengeluaran</button><button data-tab="income" class="${state.tab==='income'?'active':''}">Pemasukan</button></div></div><div id="history-list">${historyHtml()}</div></section>`;
  $('#chat-form').onsubmit=e=>{e.preventDefault();const input=$('#chat-input');const value=input.value.trim();if(!value)return;state.draft=parseTransaction(value);renderDraft(value);};
  document.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>{$('#chat-input').value=b.dataset.example;$('#chat-input').focus();});
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;renderDashboard();});
  document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete));activateIcons();
}
function reportBreakdown(kind,total){const grouped={};state.rows.filter(row=>row.kind===kind).forEach(row=>grouped[row.category]=(grouped[row.category]||0)+row.amount);const entries=Object.entries(grouped).sort((a,b)=>b[1]-a[1]);if(!entries.length)return `<div class="report-empty">Belum ada ${kind==='income'?'pemasukan':'pengeluaran'} pada bulan ini.</div>`;return `<div class="report-category-list">${entries.map(([category,amount],index)=>`<div class="report-category"><div class="report-category-line"><strong>${esc(category)}</strong><span>${money(amount)}</span></div><div class="progress"><span style="width:${amount/total*100}%;background:${kind==='income'?'#3a8890':['#d67b45','#b59043','#6977a9','#829171'][index%4]}"></span></div><small>${Math.round(amount/total*100)}% dari ${kind==='income'?'pemasukan':'pengeluaran'}</small></div>`).join('')}</div>`;}
function renderReport(){const {income,expense}=totals();const balance=income-expense;const count=state.rows.length;$('#dashboard').innerHTML=`<div class="report-summary"><div class="report-summary-heading"><span class="eyebrow">PERIODE LAPORAN</span><h2>${esc(monthName(state.month))}</h2><p>${count} transaksi tercatat pada bulan ini</p></div><div class="report-metrics"><div><span>Pemasukan</span><strong class="positive">${money(income)}</strong></div><div><span>Pengeluaran</span><strong>${money(expense)}</strong></div><div><span>Selisih</span><strong class="${balance>=0?'positive':'negative'}">${money(balance)}</strong></div></div></div><div class="report-columns"><section class="report-card"><div class="panel-head"><div><span class="eyebrow">RINCIAN</span><h2>Pemasukan per kategori</h2></div></div>${reportBreakdown('income',income)}</section><section class="report-card"><div class="panel-head"><div><span class="eyebrow">RINCIAN</span><h2>Pengeluaran per kategori</h2></div></div>${reportBreakdown('expense',expense)}</section></div><section class="history report-history"><div class="history-head"><div><span class="eyebrow">SELURUH BULAN</span><h2>Daftar transaksi</h2></div><div class="filters"><button data-tab="all" class="${state.tab==='all'?'active':''}">Semua</button><button data-tab="expense" class="${state.tab==='expense'?'active':''}">Pengeluaran</button><button data-tab="income" class="${state.tab==='income'?'active':''}">Pemasukan</button></div></div><div id="history-list">${historyHtml()}</div></section>`;document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{state.tab=button.dataset.tab;renderDashboard();});document.querySelectorAll('[data-delete]').forEach(button=>button.onclick=()=>remove(button.dataset.delete));activateIcons();}
function categoryHtml(total){const group={};state.rows.filter(r=>r.kind==='expense').forEach(r=>group[r.category]=(group[r.category]||0)+r.amount);const sorted=Object.entries(group).sort((a,b)=>b[1]-a[1]);if(!sorted.length)return `<div class="category-empty"><div class="empty-art">${icon('BarChart3',28)}</div><strong>Belum ada pengeluaran</strong><p>Catat pengeluaran untuk melihat kategori paling besar bulan ini.</p></div>`;return `<div class="category-list">${sorted.map(([name,amount],i)=>`<div class="category-row"><div class="category-line"><span><i class="category-dot" style="background:${['#d67b45','#3a8890','#b59043','#6977a9','#829171'][i%5]}"></i>${esc(name)}</span><strong>${money(amount)}</strong></div><div class="progress"><span style="width:${Math.max(3,amount/total*100)}%;background:${['#d67b45','#3a8890','#b59043','#6977a9','#829171'][i%5]}"></span></div><small>${Math.round(amount/total*100)}% dari pengeluaran</small></div>`).join('')}</div>`;}
function historyHtml(){const rows=state.rows.filter(r=>state.tab==='all'||r.kind===state.tab);if(state.loading)return `<div class="history-empty">Memuat transaksi…</div>`;if(!rows.length)return `<div class="history-empty"><div class="empty-art">${icon('Plus',25)}</div><strong>Belum ada transaksi</strong><p>Catatan yang kamu simpan akan muncul di sini.</p></div>`;return rows.map(r=>`<div class="transaction"><div class="transaction-icon ${r.kind}">${icon(r.kind==='income'?'ArrowDownLeft':'ArrowUpRight',19)}</div><div class="transaction-info"><strong>${esc(r.description)}</strong><span>${esc(r.category)} <span class="separator">·</span> ${new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(r.occurred_on+'T00:00:00Z'))}</span></div><strong class="transaction-amount ${r.kind}">${r.kind==='income'?'+':'−'}${money(r.amount)}</strong><button class="delete" data-delete="${esc(r.id)}" title="Hapus transaksi" aria-label="Hapus ${esc(r.description)}">${icon('Trash2',17)}</button></div>`).join('');}
function renderDraft(original){const d=state.draft;$('#chat-output').innerHTML=`<div class="user-bubble">${esc(original)}</div>${d.error?`<div class="reply-error">${esc(d.error)}</div>`:`<div class="draft"><div class="draft-title">${icon('Check',18)} Aku baca sebagai transaksi ini</div><div class="draft-grid"><label>Jenis<select id="draft-kind"><option value="expense" ${d.kind==='expense'?'selected':''}>Pengeluaran</option><option value="income" ${d.kind==='income'?'selected':''}>Pemasukan</option></select></label><label>Nominal (Rp)<input id="draft-amount" type="number" min="1" step="1" value="${d.amount}"></label><label>Kategori<select id="draft-category">${CATEGORIES[d.kind].map(c=>`<option ${c===d.category?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label>Tanggal<input id="draft-date" type="date" value="${d.occurred_on}"></label><label class="wide">Keterangan<input id="draft-description" maxlength="240" value="${esc(d.description)}"></label></div><div class="draft-actions"><button id="cancel-draft" class="secondary">Batal</button><button id="save-draft" class="primary">Simpan transaksi</button></div></div>`}`;
  if(!d.error){$('#draft-kind').onchange=e=>{const previous=$('#draft-category').value;$('#draft-category').innerHTML=CATEGORIES[e.target.value].map(c=>`<option ${c===previous?'selected':''}>${esc(c)}</option>`).join('');};$('#cancel-draft').onclick=()=>{$('#chat-output').innerHTML='';state.draft=null;};$('#save-draft').onclick=save;}
  activateIcons();$('#chat-output').scrollIntoView({behavior:'smooth',block:'nearest'});
}
function save(){const row={kind:$('#draft-kind').value,amount:Number($('#draft-amount').value),category:$('#draft-category').value,occurred_on:$('#draft-date').value,description:$('#draft-description').value.trim()};if(!Number.isSafeInteger(row.amount)||row.amount<=0||!row.occurred_on||!row.description){toast('Lengkapi nominal, tanggal, dan keterangan.',true);return;}const rows=[...readStored(),{...row,id:crypto.randomUUID(),created_at:new Date().toISOString()}];if(!persist(rows))return;state.draft=null;$('#chat-input').value='';toast('Transaksi tersimpan di perangkat ini.');state.month=row.occurred_on.slice(0,7);load();}
function remove(id){if(!confirm('Hapus transaksi ini?'))return;const rows=readStored().filter(row=>row.id!==id);if(!persist(rows))return;toast('Transaksi dihapus.');load();}
function load(){state.rows=readStored().filter(row=>row.occurred_on?.slice(0,7)===state.month).sort((a,b)=>b.occurred_on.localeCompare(a.occurred_on)||b.created_at.localeCompare(a.created_at));renderDashboard();}
shell();load();
