import { createClient } from '@supabase/supabase-js';
import { createIcons, ArrowDownLeft, ArrowUpRight, BarChart3, CalendarDays, Check, ChevronLeft, ChevronRight, CircleHelp, LogOut, Plus, Send, Trash2, Wallet, X } from 'lucide';
import { CATEGORIES, localDate, parseTransaction } from './parser.js';
import './style.css';

const url = import.meta.env.VITE_SUPABASE_URL || 'https://lcvrfgvhoiucotzzbfks.supabase.co';
const key = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'sb_publishable_mhfSHBeVSsQCRHy1RCPFJw_q4OwvCu2';
const db = createClient(url, key);
const icons = { ArrowDownLeft, ArrowUpRight, BarChart3, CalendarDays, Check, ChevronLeft, ChevronRight, CircleHelp, LogOut, Plus, Send, Trash2, Wallet, X };
const $ = (s) => document.querySelector(s);
const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = n => new Intl.NumberFormat('id-ID', { style:'currency', currency:'IDR', maximumFractionDigits:0 }).format(n);
const monthName = d => new Intl.DateTimeFormat('id-ID', { month:'long', year:'numeric', timeZone:'UTC' }).format(new Date(`${d}-01T00:00:00Z`));
const state = { user:null, month:localDate().slice(0,7), rows:[], draft:null, tab:'all', loading:false };
const icon = (name, size=19) => `<i data-lucide="${name}" style="width:${size}px;height:${size}px"></i>`;
function activateIcons(){ createIcons({ icons, attrs:{'stroke-width':1.8} }); }
function toast(msg, error=false){ const el=$('#toast'); el.textContent=msg; el.className=`toast show ${error?'error':''}`; clearTimeout(toast.timer); toast.timer=setTimeout(()=>el.className='toast',3500); }

function authView(){
  $('#app').innerHTML=`<main class="auth-page"><div class="auth-card"><div class="brand"><span class="mark">a.</span><span>arus</span></div><div class="auth-icon">${icon('Wallet',28)}</div><h1>Keuangan lebih jelas,<br>mulai dari satu catatan.</h1><p>Masuk dengan email untuk menyimpan catatan keuanganmu secara pribadi.</p><form id="auth-form"><label for="email">Alamat email</label><input id="email" type="email" placeholder="nama@email.com" required autocomplete="email"><button class="primary" type="submit">Kirim tautan masuk ${icon('ArrowUpRight',17)}</button></form><div id="auth-note" class="auth-note"></div><small>Catatanmu hanya dapat diakses oleh akunmu.</small></div></main><div id="toast" class="toast"></div>`;
  activateIcons(); $('#auth-form').onsubmit=async e=>{ e.preventDefault(); const btn=e.target.querySelector('button');btn.disabled=true;btn.textContent='Mengirim…'; const {error}=await db.auth.signInWithOtp({email:$('#email').value.trim(),options:{emailRedirectTo:location.origin}}); btn.disabled=false;btn.innerHTML=`Kirim tautan masuk ${icon('ArrowUpRight',17)}`;activateIcons();$('#auth-note').textContent=error?`Gagal mengirim: ${error.message}`:'Cek emailmu, lalu buka tautan masuk yang kami kirim.'; };
}

function shell(){
  $('#app').innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand"><span class="mark">a.</span><span>arus</span></div><div class="side-caption">RUANG PRIBADI</div><div class="side-active">${icon('BarChart3')} Ringkasan</div><div class="side-bottom"><div class="avatar">${esc(state.user.email?.[0]?.toUpperCase()||'A')}</div><div class="account"><strong>Akun saya</strong><span title="${esc(state.user.email)}">${esc(state.user.email)}</span></div><button class="icon-button" id="logout" title="Keluar" aria-label="Keluar">${icon('LogOut')}</button></div></aside><main class="content"><header class="topbar"><div class="mobile-brand"><span class="mark">a.</span><span>arus</span></div><span>Keuangan pribadi</span><span class="top-date">${icon('CalendarDays',16)} ${new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Jakarta'}).format(new Date())}</span></header><div class="main-inner"><section class="heading"><div><span class="eyebrow">DASHBOARD</span><h1>Ringkasan keuangan</h1><p>Pantau uang masuk dan keluar dalam satu tempat.</p></div><div class="month-control"><button id="prev" aria-label="Bulan sebelumnya">${icon('ChevronLeft',18)}</button><span>${esc(monthName(state.month))}</span><button id="next" aria-label="Bulan berikutnya">${icon('ChevronRight',18)}</button></div></section><div id="dashboard"></div></div></main></div><div id="toast" class="toast"></div>`;
  const mobileLogout=document.createElement('button');mobileLogout.className='mobile-logout';mobileLogout.setAttribute('aria-label','Keluar');mobileLogout.innerHTML=icon('LogOut',18);$('.topbar').append(mobileLogout);mobileLogout.onclick=()=>db.auth.signOut();
  $('#logout').onclick=()=>db.auth.signOut(); $('#prev').onclick=()=>shift(-1);$('#next').onclick=()=>shift(1);activateIcons();renderDashboard();
}
function shift(delta){const [y,m]=state.month.split('-').map(Number);const d=new Date(Date.UTC(y,m-1+delta,1));state.month=d.toISOString().slice(0,7);load();}
function totals(){let income=0,expense=0;for(const row of state.rows) row.kind==='income'?income+=row.amount:expense+=row.amount;return {income,expense};}
function renderDashboard(){
  const {income,expense}=totals();const balance=income-expense;
  $('#dashboard').innerHTML=`<div class="stat-grid"><div class="stat hero-stat"><div class="stat-title">Saldo bulan ini <span>${icon('Wallet',19)}</span></div><div class="stat-value">${money(balance)}</div><div class="stat-foot">${balance>=0?'Pemasukan lebih besar dari pengeluaran':'Pengeluaran melebihi pemasukan'}</div></div><div class="stat"><div class="stat-title">Pemasukan <span class="badge income">${icon('ArrowDownLeft',18)}</span></div><div class="stat-value">${money(income)}</div><div class="stat-foot">Total bulan ini</div></div><div class="stat"><div class="stat-title">Pengeluaran <span class="badge expense">${icon('ArrowUpRight',18)}</span></div><div class="stat-value">${money(expense)}</div><div class="stat-foot">Total bulan ini</div></div></div><div class="workspace"><section class="chat-panel"><div class="panel-head"><div><span class="eyebrow">CATAT TRANSAKSI</span><h2>Catat lewat chat</h2></div><span class="chat-status">Siap mencatat</span></div><div class="conversation"><div class="bot-bubble"><span class="bot-avatar">a.</span><div><strong>Halo! Mau mencatat apa hari ini?</strong><p>Ceritakan seperti sedang chat. Aku bantu baca nominal dan kategorinya.</p></div></div><div class="examples"><span>Coba tulis:</span><button data-example="Kopi susu 25 ribu tadi pagi">“Kopi susu 25 ribu tadi pagi”</button><button data-example="Terima gaji 8 juta hari ini">“Terima gaji 8 juta hari ini”</button></div><div id="chat-output"></div></div><form id="chat-form" class="chat-form"><label class="sr-only" for="chat-input">Tulis transaksi</label><input id="chat-input" placeholder="Contoh: makan siang 35 ribu" autocomplete="off" maxlength="240"><button aria-label="Kirim catatan" type="submit">${icon('Send',19)}</button></form><div class="chat-hint">${icon('CircleHelp',15)} Tinjau hasilnya sebelum menyimpan.</div></section><section class="category-panel"><div class="panel-head"><div><span class="eyebrow">PENGELUARAN</span><h2>Menurut kategori</h2></div></div>${categoryHtml(expense)}</section></div><section class="history"><div class="history-head"><div><span class="eyebrow">AKTIVITAS</span><h2>Riwayat transaksi</h2></div><div class="filters"><button data-tab="all" class="${state.tab==='all'?'active':''}">Semua</button><button data-tab="expense" class="${state.tab==='expense'?'active':''}">Pengeluaran</button><button data-tab="income" class="${state.tab==='income'?'active':''}">Pemasukan</button></div></div><div id="history-list">${historyHtml()}</div></section>`;
  $('#chat-form').onsubmit=e=>{e.preventDefault();const input=$('#chat-input');const value=input.value.trim();if(!value)return;state.draft=parseTransaction(value);renderDraft(value);};
  document.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>{$('#chat-input').value=b.dataset.example;$('#chat-input').focus();});
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;renderDashboard();});
  document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete));activateIcons();
}
function categoryHtml(total){const group={};state.rows.filter(r=>r.kind==='expense').forEach(r=>group[r.category]=(group[r.category]||0)+r.amount);const sorted=Object.entries(group).sort((a,b)=>b[1]-a[1]);if(!sorted.length)return `<div class="category-empty"><div class="empty-art">${icon('BarChart3',28)}</div><strong>Belum ada pengeluaran</strong><p>Catat pengeluaran untuk melihat kategori paling besar bulan ini.</p></div>`;return `<div class="category-list">${sorted.map(([name,amount],i)=>`<div class="category-row"><div class="category-line"><span><i class="category-dot" style="background:${['#d67b45','#3a8890','#b59043','#6977a9','#829171'][i%5]}"></i>${esc(name)}</span><strong>${money(amount)}</strong></div><div class="progress"><span style="width:${Math.max(3,amount/total*100)}%;background:${['#d67b45','#3a8890','#b59043','#6977a9','#829171'][i%5]}"></span></div><small>${Math.round(amount/total*100)}% dari pengeluaran</small></div>`).join('')}</div>`;}
function historyHtml(){const rows=state.rows.filter(r=>state.tab==='all'||r.kind===state.tab);if(state.loading)return `<div class="history-empty">Memuat transaksi…</div>`;if(!rows.length)return `<div class="history-empty"><div class="empty-art">${icon('Plus',25)}</div><strong>Belum ada transaksi</strong><p>Catatan yang kamu simpan akan muncul di sini.</p></div>`;return rows.map(r=>`<div class="transaction"><div class="transaction-icon ${r.kind}">${icon(r.kind==='income'?'ArrowDownLeft':'ArrowUpRight',19)}</div><div class="transaction-info"><strong>${esc(r.description)}</strong><span>${esc(r.category)} <span class="separator">·</span> ${new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(r.occurred_on+'T00:00:00Z'))}</span></div><strong class="transaction-amount ${r.kind}">${r.kind==='income'?'+':'−'}${money(r.amount)}</strong><button class="delete" data-delete="${esc(r.id)}" title="Hapus transaksi" aria-label="Hapus ${esc(r.description)}">${icon('Trash2',17)}</button></div>`).join('');}
function renderDraft(original){const d=state.draft;$('#chat-output').innerHTML=`<div class="user-bubble">${esc(original)}</div>${d.error?`<div class="reply-error">${esc(d.error)}</div>`:`<div class="draft"><div class="draft-title">${icon('Check',18)} Aku baca sebagai transaksi ini</div><div class="draft-grid"><label>Jenis<select id="draft-kind"><option value="expense" ${d.kind==='expense'?'selected':''}>Pengeluaran</option><option value="income" ${d.kind==='income'?'selected':''}>Pemasukan</option></select></label><label>Nominal (Rp)<input id="draft-amount" type="number" min="1" step="1" value="${d.amount}"></label><label>Kategori<select id="draft-category">${CATEGORIES[d.kind].map(c=>`<option ${c===d.category?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label>Tanggal<input id="draft-date" type="date" value="${d.occurred_on}"></label><label class="wide">Keterangan<input id="draft-description" maxlength="240" value="${esc(d.description)}"></label></div><div class="draft-actions"><button id="cancel-draft" class="secondary">Batal</button><button id="save-draft" class="primary">Simpan transaksi</button></div></div>`}`;
  if(!d.error){$('#draft-kind').onchange=e=>{const previous=$('#draft-category').value;$('#draft-category').innerHTML=CATEGORIES[e.target.value].map(c=>`<option ${c===previous?'selected':''}>${esc(c)}</option>`).join('');};$('#cancel-draft').onclick=()=>{$('#chat-output').innerHTML='';state.draft=null;};$('#save-draft').onclick=save;}
  activateIcons();$('#chat-output').scrollIntoView({behavior:'smooth',block:'nearest'});
}
async function save(){const row={kind:$('#draft-kind').value,amount:Number($('#draft-amount').value),category:$('#draft-category').value,occurred_on:$('#draft-date').value,description:$('#draft-description').value.trim()};if(!Number.isSafeInteger(row.amount)||row.amount<=0||!row.occurred_on||!row.description){toast('Lengkapi nominal, tanggal, dan keterangan.',true);return;}const btn=$('#save-draft');btn.disabled=true;btn.textContent='Menyimpan…';const {error}=await db.from('transactions').insert({...row,user_id:state.user.id});if(error){btn.disabled=false;btn.textContent='Simpan transaksi';toast(`Gagal menyimpan: ${error.message}`,true);return;}state.draft=null;$('#chat-input').value='';toast('Transaksi tersimpan.');state.month=row.occurred_on.slice(0,7);await load();}
async function remove(id){if(!confirm('Hapus transaksi ini?'))return;const {error}=await db.from('transactions').delete().eq('id',id);if(error)toast(`Gagal menghapus: ${error.message}`,true);else{toast('Transaksi dihapus.');await load();}}
async function load(){state.loading=true;renderDashboard();const start=state.month+'-01';const [y,m]=state.month.split('-').map(Number);const end=new Date(Date.UTC(y,m,1)).toISOString().slice(0,10);const {data,error}=await db.from('transactions').select('id,kind,amount,category,description,occurred_on').gte('occurred_on',start).lt('occurred_on',end).order('occurred_on',{ascending:false}).order('created_at',{ascending:false});state.loading=false;state.rows=data||[];renderDashboard();if(error)toast(`Gagal memuat: ${error.message}`,true);}
db.auth.onAuthStateChange((_event,session)=>{const was=state.user?.id;state.user=session?.user||null;if(state.user){if(was!==state.user.id){shell();load();}}else authView();});
