import { CATEGORIES, localDate } from './parser.js';
import { confirmAction, deleteOwned } from './confirm.js';
const money = n => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
const esc = v => String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const valid = n => Number.isSafeInteger(n) && n>0;
export function dueDate(month,day){const [year,m]=month.split('-').map(Number);const last=new Date(Date.UTC(year,m,0)).getUTCDate();return `${month}-${String(Math.min(day,last)).padStart(2,'0')}`;}
export function createPlanning(db,notify,getView,getMonth,getRows,reload,getUserId,accountOptions){
  let budgets=[],recurring=[];
  const root=()=>document.querySelector('#dashboard');
  const error=e=>notify(e.message||'Gagal menyimpan.',true);
  async function fetchData(){const [b,r]=await Promise.all([db.from('budget_limits').select('id,month,category,amount').eq('month',getMonth()+'-01'),db.from('recurring_items').select('id,title,kind,amount,category,day_of_month,active').order('day_of_month')]);if(b.error||r.error)throw b.error||r.error;budgets=b.data||[];recurring=r.data||[];}
  function budgetView(){const rows=getRows().filter(r=>r.occurred_on.startsWith(getMonth())&&r.kind==='expense');const spent=cat=>rows.filter(r=>r.category===cat).reduce((sum,r)=>sum+r.amount,0);root().innerHTML=`<div class="feature-grid"><section class="feature-card"><span class="eyebrow">ANGGARAN BULAN INI</span><h2>Atur batas kategori</h2><form id="budget-form" class="feature-form"><label>Kategori<select name="category">${CATEGORIES.expense.map(c=>`<option>${esc(c)}</option>`).join('')}</select></label><label>Batas pengeluaran (Rp)<input name="amount" type="number" min="1" required placeholder="1000000"></label><button class="primary">Simpan anggaran</button></form></section><section class="feature-card"><span class="eyebrow">PANDUAN</span><h2>Pantau pengeluaran</h2><p class="muted">Anggaran berlaku untuk bulan yang sedang dipilih. Ubah bulan dengan tombol panah di atas. Menyimpan kategori yang sama akan memperbarui batasnya.</p><p class="muted">Jumlah terpakai dihitung dari transaksi pengeluaran pada kategori tersebut.</p></section></div><div class="goal-list">${budgets.length?budgets.map(b=>{const used=spent(b.category),pct=Math.min(100,Math.round(used/b.amount*100));return `<section class="feature-card"><div class="feature-row"><div><span class="eyebrow">ANGGARAN</span><h2>${esc(b.category)}</h2></div><button class="delete" data-budget-delete="${b.id}">Hapus</button></div><div class="goal-amount"><strong>${money(used)}</strong><span>dari ${money(b.amount)}</span></div><div class="progress"><span style="width:${pct}%;background:${used>b.amount?'#c96351':used>=b.amount*.8?'#d79550':'#3a8890'}"></span></div><small>${used>b.amount?`Melebihi batas ${money(used-b.amount)}`:`Sisa ${money(b.amount-used)}`}</small></section>`}).join(''):'<div class="feature-card feature-empty">Belum ada anggaran untuk bulan ini.</div>'}</div>`;
    document.querySelector('#budget-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,amount=Number(f.elements.amount.value),category=f.elements.category.value;if(!valid(amount))return notify('Isi batas yang valid.',true);const {error:err}=await db.from('budget_limits').upsert({user_id:getUserId(),month:getMonth()+'-01',category,amount},{onConflict:'user_id,month,category'});if(err)return error(err);notify('Anggaran disimpan.');await refresh('budget');};
    document.querySelectorAll('[data-budget-delete]').forEach(b=>b.onclick=async()=>{if(!await confirmAction('Hapus anggaran kategori ini?'))return;try{await deleteOwned(db,'budget_limits',b.dataset.budgetDelete);}catch(err){return error(err);}await refresh('budget');});
  }
  function recurringView(){const month=getMonth(),all=getRows(),today=localDate();root().innerHTML=`<div class="feature-grid"><section class="feature-card"><span class="eyebrow">JADWAL BULANAN</span><h2>Tambah transaksi berulang</h2><form id="recurring-form" class="feature-form"><label>Nama<input name="title" maxlength="100" required placeholder="Contoh: Bayar internet"></label><label>Jenis<select name="kind"><option value="expense">Pengeluaran</option><option value="income">Pemasukan</option></select></label><label>Nominal (Rp)<input name="amount" type="number" min="1" required></label><label>Kategori<select name="category">${CATEGORIES.expense.map(c=>`<option>${esc(c)}</option>`).join('')}</select></label><label>Tanggal setiap bulan (1–31)<input name="day" type="number" min="1" max="31" required value="1"></label><button class="primary">Simpan jadwal</button></form></section><section class="feature-card"><span class="eyebrow">KALENDER TAGIHAN</span><h2>Jadwal ${esc(month)}</h2><p class="muted">Tanggal 29–31 akan jatuh pada hari terakhir jika bulannya lebih pendek. Tekan Catat transaksi setelah pembayaran terjadi; jadwal tidak otomatis mengurangi saldo.</p><p class="muted">Status tercatat dicek per bulan sehingga satu tagihan tidak dicatat dua kali.</p></section></div><div class="bill-list">${recurring.length?recurring.map(item=>{const due=dueDate(month,item.day_of_month),recorded=all.some(r=>r.recurring_item_id===item.id&&r.recurring_month===month+'-01'),late=!recorded&&item.active&&due<today;return `<section class="feature-card"><div class="feature-row"><div><span class="eyebrow">${item.kind==='expense'?'TAGIHAN':'PEMASUKAN'} · ${esc(due)}</span><h2>${esc(item.title)}</h2></div><button class="delete" data-recurring-delete="${item.id}">Hapus</button></div><div class="bill-summary"><strong>${money(item.amount)}</strong><span>${esc(item.category)}</span></div><p class="muted">${recorded?'Sudah dicatat bulan ini':!item.active?'Jadwal dijeda':late?'Lewat tanggal, belum dicatat':'Belum dicatat'}</p><label class="recurring-account">Akun/Dompet<select data-recurring-account="${item.id}">${accountOptions()}</select></label><div class="feature-actions"><button class="primary" data-recurring-record="${item.id}" ${recorded||!item.active?'disabled':''}>Catat transaksi</button><button class="secondary" data-recurring-toggle="${item.id}">${item.active?'Jeda':'Aktifkan'}</button></div></section>`}).join(''):'<div class="feature-card feature-empty">Belum ada jadwal bulanan.</div>'}</div>`;
    const form=document.querySelector('#recurring-form');form.elements.kind.onchange=()=>{form.elements.category.innerHTML=CATEGORIES[form.elements.kind.value].map(c=>`<option>${esc(c)}</option>`).join('');};
    form.onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,amount=Number(f.elements.amount.value),day=Number(f.elements.day.value);if(!valid(amount)||!Number.isInteger(day)||day<1||day>31)return notify('Nominal atau tanggal tidak valid.',true);const {error:err}=await db.from('recurring_items').insert({title:f.elements.title.value.trim(),kind:f.elements.kind.value,amount,category:f.elements.category.value,day_of_month:day});if(err)return error(err);notify('Jadwal disimpan.');await refresh('recurring');};
    document.querySelectorAll('[data-recurring-record]').forEach(b=>b.onclick=async()=>{const item=recurring.find(r=>r.id===b.dataset.recurringRecord);b.disabled=true;const {error:err}=await db.from('transactions').insert({kind:item.kind,amount:item.amount,category:item.category,description:item.title,occurred_on:dueDate(month,item.day_of_month),recurring_item_id:item.id,recurring_month:month+'-01',account_id:document.querySelector(`[data-recurring-account=\"${item.id}\"]`)?.value||null});if(err){b.disabled=false;return error(err);}notify('Transaksi dicatat.');await reload();await refresh('recurring');});
    document.querySelectorAll('[data-recurring-toggle]').forEach(b=>b.onclick=async()=>{const item=recurring.find(r=>r.id===b.dataset.recurringToggle);const {error:err}=await db.from('recurring_items').update({active:!item.active}).eq('id',item.id);if(err)return error(err);await refresh('recurring');});
    document.querySelectorAll('[data-recurring-delete]').forEach(b=>b.onclick=async()=>{if(!await confirmAction('Hapus jadwal ini? Transaksi yang sudah tercatat tetap ada.'))return;try{await deleteOwned(db,'recurring_items',b.dataset.recurringDelete);}catch(err){return error(err);}await reload();await refresh('recurring');});
  }
  async function refresh(view){root().innerHTML='<div class="feature-card feature-empty">Memuat data…</div>';try{await fetchData();if(getView()!==view)return;if(view==='budget')budgetView();else recurringView();}catch(e){root().innerHTML='<div class="feature-card feature-empty">Gagal memuat. Buka menu lagi untuk mencoba ulang.</div>';error(e);}}
  return {refresh};
}
